<script setup>
import { useForm, usePage } from '@inertiajs/vue3'
import { computed } from 'vue'

const flash = computed(() => usePage().props.flash)

const form = useForm({ pilot_token: '' })

function submit() {
    form.post('/login', { preserveScroll: true })
}
</script>

<template>
    <div class="min-h-screen flex items-center justify-center px-4" style="background-color: var(--color-surface-base);">
        <div class="w-full max-w-md">

            <!-- Header -->
            <div class="text-center mb-8">
                <h1 class="text-3xl font-bold mb-1">
                    <span style="color: var(--color-accent);">ProjectHub</span>
                    <span style="color: var(--color-text-primary);"> LLM</span>
                </h1>
                <p class="text-sm" style="color: var(--color-text-secondary);">
                    Multi-agent project management
                </p>
            </div>

            <!-- Card -->
            <div class="rounded-xl p-8" style="background-color: var(--color-surface-elevated); border: 1px solid var(--color-surface-border);">

                <h2 class="text-lg font-semibold mb-1" style="color: var(--color-text-primary);">Pilot Login</h2>
                <p class="text-sm mb-6" style="color: var(--color-text-secondary);">
                    Enter the pilot token generated by your LLM agent to access your workspaces.
                </p>

                <!-- Error -->
                <div v-if="flash?.error" class="mb-4 px-4 py-3 rounded-lg text-sm" style="background-color: rgba(239,68,68,0.1); color: var(--color-danger); border: 1px solid rgba(239,68,68,0.2);">
                    {{ flash.error }}
                </div>

                <form @submit.prevent="submit" class="space-y-5">
                    <div>
                        <label class="block text-xs font-medium mb-2" style="color: var(--color-text-secondary);">PILOT TOKEN</label>
                        <input
                            v-model="form.pilot_token"
                            type="text"
                            placeholder="plt_..."
                            autocomplete="off"
                            class="w-full px-4 py-3 rounded-lg text-sm outline-none transition-colors"
                            style="font-family: var(--font-mono); background-color: var(--color-surface-base); border: 1px solid var(--color-surface-border); color: var(--color-text-primary);"
                            onfocus="this.style.borderColor='var(--color-accent)'"
                            onblur="this.style.borderColor='var(--color-surface-border)'"
                        />
                        <p v-if="form.errors.pilot_token" class="mt-1 text-xs" style="color: var(--color-danger);">
                            {{ form.errors.pilot_token }}
                        </p>
                    </div>

                    <button
                        type="submit"
                        :disabled="form.processing"
                        class="w-full py-3 rounded-lg text-sm font-medium transition-opacity"
                        style="background-color: var(--color-accent); color: #0d0f14;"
                        :style="form.processing ? 'opacity:0.6' : ''"
                    >
                        {{ form.processing ? 'Connecting...' : 'Connect to Agent' }}
                    </button>
                </form>

                <p class="mt-6 text-xs text-center" style="color: var(--color-text-muted);">
                    Token is generated by your agent via <span style="font-family: var(--font-mono);">POST /api/v1/auth/pilot-token</span>.<br>
                    Valid for 15 minutes.
                </p>
            </div>
        </div>
    </div>
</template>
