<script setup>
import { useForm, usePage } from '@inertiajs/vue3'
import { computed, ref } from 'vue'
import { Link } from '@inertiajs/vue3'

const props = defineProps({
    tokenError: { type: String, default: null },
})

const flash = computed(() => usePage().props.flash)

// Detect ?token= in URL — server already tried to process it server-side.
// If we're still on the login page it means it failed (tokenError will be set).
const urlToken = new URLSearchParams(window.location.search).get('token')
const autoAttempted = ref(!!urlToken)

const form = useForm({ pilot_token: '' })

function submit() {
    form.post('/login', { preserveScroll: true })
}

const helpOpen = ref(false)
const copiedHelp = ref(false)

const helpPrompt = `Generate a pilot token for me so I can log into the ProjectHub LLM dashboard.

Call this endpoint with your API key:

POST ${window.location.origin}/api/v1/auth/pilot-token
Authorization: Bearer <your sk_proj_ api key>

Give me the value of the "token" field from the response. It will start with plt_`

function copyHelp() {
    navigator.clipboard.writeText(helpPrompt)
    copiedHelp.value = true
    setTimeout(() => copiedHelp.value = false, 2000)
}
</script>

<template>
    <div class="min-h-screen flex items-center justify-center px-4 py-12" style="background-color: var(--color-surface-base);">
        <div class="w-full max-w-md space-y-4">

            <!-- Header -->
            <div class="text-center mb-8">
                <h1 class="text-3xl font-bold mb-1">
                    <span style="color: var(--color-accent);">ProjectHub</span>
                    <span style="color: var(--color-text-primary);"> LLM</span>
                </h1>
                <p class="text-sm" style="color: var(--color-text-secondary);">
                    Multi-agent project management
                </p>
            </div>

            <!-- Login Card -->
            <div class="rounded-xl p-8" style="background-color: var(--color-surface-elevated); border: 1px solid var(--color-surface-border);">

                <h2 class="text-lg font-semibold mb-1" style="color: var(--color-text-primary);">Pilot Login</h2>
                <p class="text-sm mb-6" style="color: var(--color-text-secondary);">
                    Enter the pilot token generated by your LLM agent.
                </p>

                <!-- Auto-login processing indicator -->
                <div v-if="autoAttempted && !tokenError" class="mb-4 px-4 py-3 rounded-lg text-sm flex items-center gap-2"
                    style="background-color: rgba(56,189,248,0.08); color: var(--color-accent); border: 1px solid rgba(56,189,248,0.2);">
                    <svg class="w-4 h-4 animate-spin shrink-0" fill="none" viewBox="0 0 24 24">
                        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/>
                        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z"/>
                    </svg>
                    Verifying login link…
                </div>

                <!-- Token link error -->
                <div v-if="tokenError" class="mb-4 px-4 py-3 rounded-lg text-sm"
                    style="background-color: rgba(239,68,68,0.1); color: var(--color-danger); border: 1px solid rgba(239,68,68,0.2);">
                    {{ tokenError }}
                </div>

                <!-- Flash error -->
                <div v-if="flash?.error" class="mb-4 px-4 py-3 rounded-lg text-sm"
                    style="background-color: rgba(239,68,68,0.1); color: var(--color-danger); border: 1px solid rgba(239,68,68,0.2);">
                    {{ flash.error }}
                </div>

                <form @submit.prevent="submit" class="space-y-5">
                    <div>
                        <label class="block text-xs font-medium mb-2" style="color: var(--color-text-secondary);">PILOT TOKEN</label>
                        <input
                            v-model="form.pilot_token"
                            type="text"
                            placeholder="plt_..."
                            autocomplete="off"
                            class="w-full px-4 py-3 rounded-lg text-sm outline-none transition-colors"
                            style="font-family: var(--font-mono); background-color: var(--color-surface-base); border: 1px solid var(--color-surface-border); color: var(--color-text-primary);"
                            onfocus="this.style.borderColor='var(--color-accent)'"
                            onblur="this.style.borderColor='var(--color-surface-border)'"
                        />
                        <p v-if="form.errors.pilot_token" class="mt-1 text-xs" style="color: var(--color-danger);">
                            {{ form.errors.pilot_token }}
                        </p>
                    </div>

                    <button
                        type="submit"
                        :disabled="form.processing"
                        class="w-full py-3 rounded-lg text-sm font-medium transition-opacity"
                        style="background-color: var(--color-accent); color: #0d0f14;"
                        :style="form.processing ? 'opacity:0.6' : ''"
                    >
                        {{ form.processing ? 'Connecting...' : 'Connect to Agent' }}
                    </button>
                </form>

                <!-- Help toggle -->
                <button @click="helpOpen = !helpOpen"
                    class="mt-5 w-full flex items-center justify-between text-xs px-4 py-2.5 rounded-lg transition-colors"
                    :style="helpOpen
                        ? 'background-color: rgba(56,189,248,0.08); color: var(--color-accent); border: 1px solid rgba(56,189,248,0.2);'
                        : 'background-color: var(--color-surface-base); color: var(--color-text-muted); border: 1px solid var(--color-surface-border);'">
                    <span class="flex items-center gap-2">
                        <svg class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                        How do I get a pilot token?
                    </span>
                    <svg class="w-3.5 h-3.5 transition-transform" :class="helpOpen ? 'rotate-180' : ''" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M19 9l-7 7-7-7" />
                    </svg>
                </button>
            </div>

            <!-- Help panel -->
            <div v-if="helpOpen" class="rounded-xl overflow-hidden" style="border: 1px solid var(--color-surface-border);">

                <!-- Header -->
                <div class="px-5 py-4" style="background-color: var(--color-surface-elevated); border-bottom: 1px solid var(--color-surface-border);">
                    <h3 class="text-sm font-semibold mb-1" style="color: var(--color-text-primary);">Ask your agent for a token</h3>
                    <p class="text-xs" style="color: var(--color-text-secondary);">Copy this prompt and send it to your AI agent.</p>
                </div>

                <!-- Steps -->
                <div class="px-5 py-4 space-y-3" style="background-color: var(--color-surface-elevated);">
                    <div v-for="(item, i) in [
                        'Open the AI agent connected to your ProjectHub workspace',
                        'Paste the prompt below into the chat',
                        'Copy the <code>plt_...</code> token from the agent\'s response',
                        'Paste it in the field above and click Connect',
                    ]" :key="i" class="flex items-start gap-3">
                        <span class="shrink-0 mt-0.5 w-5 h-5 rounded-full text-xs flex items-center justify-center font-bold"
                            style="background-color: rgba(56,189,248,0.15); color: var(--color-accent);">{{ i + 1 }}</span>
                        <span class="text-xs" style="color: var(--color-text-secondary);"
                            v-html="item.replace(/<code>/g, '<code style=\'font-family: var(--font-mono); color: var(--color-accent); background: rgba(56,189,248,0.08); padding: 1px 5px; border-radius: 4px;\'>').replace(/<\/code>/g, '</code>')"></span>
                    </div>
                </div>

                <!-- Prompt box -->
                <div style="border-top: 1px solid var(--color-surface-border);">
                    <div class="flex items-center justify-between px-4 py-2.5"
                        style="background-color: var(--color-surface-base); border-bottom: 1px solid var(--color-surface-border);">
                        <span class="text-xs" style="color: var(--color-text-muted); font-family: var(--font-mono);">prompt to paste</span>
                        <button @click="copyHelp"
                            class="flex items-center gap-1.5 text-xs px-3 py-1 rounded transition-all"
                            :style="copiedHelp
                                ? 'background-color: rgba(34,197,94,0.15); color: var(--color-success); border: 1px solid rgba(34,197,94,0.3);'
                                : 'background-color: var(--color-surface-elevated); color: var(--color-text-secondary); border: 1px solid var(--color-surface-border);'">
                            <svg v-if="!copiedHelp" class="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                            </svg>
                            <svg v-else class="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7" />
                            </svg>
                            {{ copiedHelp ? 'Copied!' : 'Copy' }}
                        </button>
                    </div>
                    <pre class="p-4 text-xs leading-relaxed whitespace-pre-wrap overflow-x-auto"
                        style="background-color: var(--color-surface-base); color: var(--color-text-secondary); font-family: var(--font-mono);">{{ helpPrompt }}</pre>
                </div>
            </div>

            <!-- Register link -->
            <p class="text-center text-xs" style="color: var(--color-text-muted);">
                First time?
                <Link href="/register" style="color: var(--color-accent);">Register your organization</Link>
            </p>

        </div>
    </div>
</template>
